name: Build docs

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      # Create an access token for the Github Actions Bot app. This one has permissions
      # to push directly to this repository (only!) without required status checks.
      # - uses: actions/create-github-app-token@v1
      #   id: github-actions-bot-app-token
      #   with:
      #     app-id: 48725422
      #     private-key: ${{ secrets.APOLLO_GITHUB_ACTIONS_BOT_PRIVATE_KEY }}
      #     repositories: ${{ github.repository }}
      #     owner: ${{ github.repository_owner }}

      # Check out the repository, using the Github Actions Bot app's token so that we
      # can push later and override required statuses.
      - name: Checkout repo
        uses: actions/checkout@v4
        # with:
        #   token: ${{ steps.github-actions-bot-app-token.outputs.token }}

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: "yarn"

      - run: yarn install --immutable

      - name: Create Docs
        run: |
          yarn workspaces foreach --all --include "@apollo/*" run build
          yarn workspaces foreach --all --include "@apollo/*" exec api-extractor run
          yarn workspace monorepo docs

      # - name: Commit changes back
      #   uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_message: "Update Docs"
      #     push_options: ""
      #     skip_dirty_check: false

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "[chore] Update Docs"
          commit-message: "Update Docs"
          branch: "pr/update-docs"
          delete-branch: true
